### ISSUE TITLE
Check for non-emptiness of response parameters

### ISSUE THREAD

**Issue by jsor** [ETSGlobal/ETSPaymentOgoneBundle#30]
Ist there a reason for the non-emptiness check of response parameters:
https://github.com/ETSGlobal/ETSPaymentOgoneBundle/blob/master/Response/FeedbackResponse.php#L44

I noticed that when you hit the cancel button on the payment page, you get redirected to the CANCELURL with an empty NCERROR parameter which results in an `Feedback parameter [NCERROR] was not sent with the Request.` exception.

![Ogone Payment](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/17951/77888/9Hz12ni0Bn4W3AJ/ogone.png)

**Comment by ch3ric** [comment]
Hello @jsor!

Thanks for this comment and sorry for this late answer...

I found out the non-emptiness check you're talking about was added in this commit: https://github.com/ETSGlobal/ETSPaymentOgoneBundle/commit/542ec18a23530da5d33b6efad3640f40bf9f8986#diff-6efa7886f3f68e5fc30a709ed7b46b57 by @baruica
to fix this issue : https://github.com/ETSGlobal/ETSPaymentOgoneBundle/issues/27

So it seems dangerous to remove this check.

Did you find another way to fix this issue?
I guess you've found a workaround since then.

**Comment by jsor** [comment]
IIRC, i had to do cancellation of the order manually (pseudo-code):

```php
if ('1' === $request->get('STATUS')) {
    $this->paymentCanceller->cancelOrderPayment($order, $this->feedbackResponse);
} else {
    $this->ogone->handleTransactionFeedback($order->paymentInstruction());
}
```
